version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: medical_telegram_warehouse_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: medical_warehouse
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with existing PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medical_network

volumes:
  postgres_data:

networks:
  medical_network: